### ISSUE TITLE
Feature Request (kind of)

### ISSUE THREAD

**Issue by km-coded** [MaffooClock/ESP32RotaryEncoder#2]
![photo_2023-10-30_22-48-14](https://github.com/MaffooClock/ESP32RotaryEncoder/assets/3342605/6ef3be88-2a74-48fa-9e87-f90243320e35)
I found your very lightweight lib useful for the use of an rotary encoder, suitable for an oscilloscope. 
but i needed more of a simple up/down function for navigation through the menu and simple changing v/div and ms/div,
so i wrote this little workaround for the project, but i will keep using it for the next project. 
maybe you can include it as another option instead of a range of values to just simulate up/down.

```cpp
  rotaryEncoder.setEncoderType( EncoderType::HAS_PULLUP );
  rotaryEncoder.setBoundaries( -1, 1, false ); // reduces rotary encoder motion from min/max to up/down in endless loop
  rotaryEncoder.onTurned( &knobCallback );
  rotaryEncoder.onPressed( &buttonCallback );
  rotaryEncoder.begin();
void knobCallback( int value )
{
  if(rotaryEncoder.getEncoderValue() == 1){
    //Serial.println("up");	// for debugging
    btnpl = 1;
  }
  else if(rotaryEncoder.getEncoderValue() == -1){
    //Serial.println("down");	// for debugging
    btnmn = 1;
  }
  else {
    btnpl = 0;
    btnmn = 0;
  }
  lastValue =  rotaryEncoder.getEncoderValue();
  //Serial.printf( "Value: %i\n", value );	// for debugging
}
```

and second thing:
i wanted to use the push button for the menu system with ok/back. i tried some millis() function for pressed/released and so, but it didn't work out. maybe you can implement simple short/long press to the push button part?

**Comment by MaffooClock** [comment]
> maybe you can include it as another option instead of a range of values to just simulate up/down.

That's not a bad idea -- perhaps, I could add a `.startValue( int )` that could be used to set the initial value for the endless increment/decrement.  And perhaps a `.valueStep( int )` that could be used to set the increment/decrement amount.

-----

> maybe you can implement simple short/long press to the push button part?

Heh, I was wondering when this question would come up.  I'd thought of it, too, actually.  But I was trying to keep this simple -- at least at first, just to ensure things are stable before we start adding things.

Here's an idea that'd be a workaround for now: there's another library just for buttons that does exactly what you're asking for, but I can't quite remember what it's called.  I'll try to find it.  But you could use that, then instantiate the RotaryEncoder object like this:

```c++
// Example 1: instantiate a rotary encoder without a pushbutton
RotaryEncoder rotaryEncoder( DI_ENCODER_A, DI_ENCODER_B );

// Example 2: instantiate a rotary encoder without a pushbutton, but with a VCC pin
RotaryEncoder rotaryEncoder( DI_ENCODER_A, DI_ENCODER_B, -1, DO_ENCODER_VCC );
```

... so that the ESP32RotaryEncoder library ignores the pushbutton, and the other library for the pushbutton can be used for that instead.

**Comment by MaffooClock** [comment]
Update: I've just pushed commit 509eb34, which adds the ability to specify a step value.  So now you can have the value increment/decrement by some value besides the default `1`.

In that commit, I've also broken out the boundary settings into separate `setMinValue( int )` and `setMaxValue( int )` to make it easier to change the boundaries during runtime (say, if you're navigating a multi-level menu, for example).  This isn't new functionality, just simplified.

I have not (yet?) implemented the infinite boundaries capability you mentioned.  But really, this doesn't have to be baked in -- since the minimum and maximum values are just 32-bit `int` types, you could set the boundaries to -2,147,483,648 and 2,147,483,647 for a "virtually infinite" behavior.  If that range isn't wide enough, then... 😳

Lastly, completely unrelated to this issue: I've added some ESP32-IDF native logging in commit f793f73 to make it easier to test and debug.

I have not pushed a new release to PlatformIO Registry or Arduino Library yet (but soon!), so if you want to use these, you'll need to get them straight from this repo.

**Comment by MaffooClock** [comment]
Hmm... I've just re-read your original post, and now I've realized that evidently I have confused myself:

>  i needed more of a simple up/down function

Yeah, not sure how the hell my mind converted that to a "infinite boundaries" concept.  I'm an idiot, heh.

So what you _really_ asked for was, instead of an integer value that increases or decreases, you just want to know if the knob was turned right or left, and then take some action based on which event occurred.

So, that's pretty simple, and we don't need to change anything in the library.  In fact, you almost have it.  Try this:

```c++
// You had this part correct, so leave it like you have it
rotaryEncoder.setBoundaries( -1, 1, false );


/**
 *  Add these flags and functions:
 */

volatile bool turnedRightFlag = false;
volatile bool turnedLeftFlag = false;

void turnedRight()
{
  // Do whatever you needed to do when the knob is turned right (e.g. travel down the menu)

  // Set this back to false so we can watch for the next move
  turnedRightFlag = false;
}

void turnedLeft()
{
  // Do whatever you needed to do when the knob is turned left (e.g. travel up the menu)

  // Set this back to false so we can watch for the next move
  turnedLeftFlag = false;
}


/**
 *  Now make your callback look more like this:
 */

void knobCallback( int value )
{
  // Don't do anything if either flag is set;
  // it means we haven't taken action yet
  if( turnedRightFlag || turnedLeftFlag )
    return;

  // Set a flag that we can look for in `loop()`
  // so that we know we have something to do
  switch( value )
  {
    case 1:
      turnedRightFlag = true;
    break;

    case -1:
      turnedLeftFlag = true;
    break;
  }

  // Override the tracked value back to 0 so that 
  // we can continue tracking right/left events
  rotaryEncoder.setEncoderValue( 0 );
}


/**
 *  Use your loop to watch the flags and call the functions
 */

void loop()
{
  if( turnedRightFlag )
    turnedRight();

  else if( turnedLeftFlag )
    turnedLeft();
}
```

This is untested -- I just pulled it out of my _ahem_.  But it should get you 98% of the way.

While writing this up, I thought more about including this type of functionality into the library since the point of having the library is to make things simple.  However, I'm concerned about adding too much and potentially causing confusion.

What I can do, however, is add a new example from the above 👍

**Comment by km-coded** [comment]
https://github.com/nightflasher/esp32_oscilloscope
Here you can see the entire project,with this menu system.

**Comment by km-coded** [comment]
tested your script, doesn't work in my case, because the loop() section stays empty and switches between the two cores. turning the knob stops everything.

**Comment by MaffooClock** [comment]
> the loop() section stays empty and switches between the two cores

I don't think I understand what you're saying.

As I understand it, the `loop()` runs on core 1, and internal operations (like maintaining WiFi or Bluetooth connections, timer ISRs, among other things) all run on core 0.   There's a way to use core 0, but only if you know what you're doing and understand the ramifications (e.g. you don't need RF or timer interrupts).

Personally, nearly all of my Arduino programming never uses the `loop()` -- I implement timers, interrupts, schedulers, etc. to handle various tasks (and, therefore, rarely use `delay()`).  For your example, though, I tried to keep it simple.

As I said, the code I offered above was untested.  However, I have used that to create a third example that worked exactly as I've described: [examples/LeftOrRight](https://github.com/MaffooClock/ESP32RotaryEncoder/blob/main/examples/LeftOrRight/LeftOrRight.ino)

![Screenshot](https://github.com/MaffooClock/ESP32RotaryEncoder/assets/540782/29cd9b31-1f90-4054-94c2-9bbd7c94bc69)

**Comment by MaffooClock** [comment]
I've added the ability to get the duration of the button press, which should enable you to determine a "long press" versus a "normal press."

This is a breaking change -- you'll need to change your button callback to accept an argument of type `long`, which will be the duration in milliseconds that the button was held before being released.

This is now in [release v1.1.0](https://github.com/MaffooClock/ESP32RotaryEncoder/releases/tag/v1.1.0), which has been pushed to the [PlatformIO Registry](https://registry.platformio.org/libraries/maffooclock/ESP32RotaryEncoder?version=1.1.0).  The Arduino Library should pick up the new version within a day or two.

I think we've address the items you brought up, so I'll close this now.
